# Lab 1 : Numpy Introduction Assignment
    1. 4 way of dot product
    2. reshape(-1,1) --> for arranging in 1 column
    3. reshape(-1) --> for arranging in 1 row
    4. to set any target value as True and other as False in array
    5. copy()
    6. view()
    7. Broadcasting

In [2]:
import numpy as np

In [3]:
n1 = np.arange(12).reshape(3,4)
n1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
n2 = np.arange(12).reshape(4,3)
n2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### 4 ways of dot product

In [5]:
# method 1
n3 = n1.dot(n2)
n3

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [6]:
# method 2
n3 = np.dot(n1,n2)
n3

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [7]:
# method 3
n3=n1@n2
n3

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [8]:
# method 4
n3 = np.matmul(n1,n2)
n3

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [9]:
a = np.arange(12)

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### for aranging array in 1 column

In [11]:
a.reshape(-1,1) 

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [12]:
a1 = np.arange(12)

In [13]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
a1.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### for aranging array in 1 row 

In [15]:
a1.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
a2 = np.random.randint(1, 100, size=(5, 6))
a2

array([[19, 68, 59, 70, 58, 17],
       [73, 91, 75,  3, 67, 63],
       [77, 91, 46, 65, 93,  3],
       [80, 63, 72, 84, 27,  5],
       [64, 53, 89, 88, 76, 72]])

### to set any target value as True and other as False

In [17]:
x = 79
a3 = a2 == x
a3

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

### copy() 

In [18]:
c1 = np.arange(12).reshape(3,4)
c1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
c2 = c1.copy() # it is cresting copy of c1 array
c2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### view()

In [30]:
v1 = np.arange(12).reshape(3,4)
v1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
v2 = v1.view()
v2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
v2+=1 # lets do some operation on view array
v2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
v1 # it affect to actual array also

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Broadcasting

In [34]:
b1 = np.arange(4)
b1

array([0, 1, 2, 3])

In [42]:
b2 = np.arange(4,8).reshape(-1,1)
b2

array([[4],
       [5],
       [6],
       [7]])

In [43]:
b1 + b2 #it is adding like[4*4] + [4*4] matrix

array([[ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

In [44]:
b1 * b2 

array([[ 0,  4,  8, 12],
       [ 0,  5, 10, 15],
       [ 0,  6, 12, 18],
       [ 0,  7, 14, 21]])

In [46]:
b1 * (b1.reshape(-1,1))

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])