# -->numpy array | jax -->panda | palar | dask
#appachar flow


In [2]:
import numpy as np
a = np.array([1,2,3]) #1D array
print(a)

[1 2 3]


In [3]:
# 2D 3D array
b = np.array([[1,2,3],[4,5,6]])
b


array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b.shape

(2, 3)

In [5]:
b.ndim

2

# arange()
reshape --> to arrange in 1d to 2d or any dimantion
np.arange(start=1, stop=10, step=3) --> 3 aarguments

In [6]:
c = np.arange(start=1,stop = 13, step = 5)
c

array([ 1,  6, 11])

In [7]:
np.arange(2,6)

array([2, 3, 4, 5])

In [8]:
d = np.arange(1,13,1)

In [9]:
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# reshape()


In [10]:
f = d.reshape(2,6)#array will convert into the 2 rows and 6 columns
f

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [11]:
e = d.reshape(4,3)#4 rows and 3 columns
e

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
h = d.reshape(3,4)
h

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
e.shape

(4, 3)

In [14]:
e.ndim

2

In [15]:
g=d.reshape(2, 3, 2)
g

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [16]:
g.shape

(2, 3, 2)

In [17]:
g.ndim

3

In [18]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [19]:
np.arange(48).reshape(2,2,3,4)

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]],


       [[[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]],

        [[36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]]])

# indexing and slicing

In [20]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
a1[5]

5

In [24]:
a1[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a1[:5]

array([0, 1, 2, 3, 4])

In [26]:
a1[3:8]

array([3, 4, 5, 6, 7])

In [27]:
a1[3:8:2]

array([3, 5, 7])

In [28]:
a1[-10:-5:2]

array([0, 2, 4])

In [29]:
a1[-1:-8:-2]

array([9, 7, 5, 3])

In [30]:
a2[2,2]

10

In [31]:
a2[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [32]:
a2[1:,1]

array([5, 9])

In [33]:
a2[1:,0::3]

array([[ 4,  7],
       [ 8, 11]])

In [34]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
a3[1,0,1]

5

In [36]:
a3[1,1]

array([6, 7])

In [37]:
a3[0,1,1]

3

In [38]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#### Assignment
#### if there is a same number in array thep at that place print true othervise false
#### 4th way of dot product


In [39]:
np.random.randint(1,100,24).reshape(6,4)

array([[74, 14, 20, 19],
       [82, 77, 64, 66],
       [18, 21, 62, 60],
       [13, 24, 80, 97],
       [85, 52, 17, 93],
       [48, 34, 80,  3]])

In [41]:
g  = np.random.randint(1,100,24).reshape(-1,1)
g

array([[33],
       [86],
       [98],
       [79],
       [27],
       [67],
       [99],
       [42],
       [37],
       [37],
       [96],
       [10],
       [ 3],
       [58],
       [93],
       [34],
       [54],
       [30],
       [50],
       [ 9],
       [65],
       [22],
       [ 6],
       [29]])